version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for package.json in the root directory
    directory: "/"
    # Check for updates on Thursdays
    schedule:
      interval: "weekly"
      day: "thursday"
    # Set a maximum number of open pull requests for version updates
    open-pull-requests-limit: 10
    # Assign PRs to repository maintainer  
    assignees:
      - "tsmarvin"
    # Add labels to PRs
    labels:
      - "dependencies"
      - "npm"
    # Group dependency updates to reduce PR noise
    groups:
      dev-dependencies:
        dependency-type: "development"
      production-dependencies:
        dependency-type: "production"