name: Deploy Develop Branch to Sub-directory (DISABLED)

# This workflow is currently disabled because GitHub Actions deployment
# only supports deploying to the root domain, not subdirectories.
# Subdirectory previews like test-PR146/ are not possible with GitHub Actions.

on:
  # Disabled - uncomment to re-enable if alternative hosting is configured
  # push:
  #   branches: [ develop ]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number for deployment path'
        required: false
        type: string

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-develop"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow Disabled Notice
        run: |
          echo "::warning::This workflow is disabled because GitHub Actions deployment does not support subdirectories."
          echo "::warning::For develop branch previews, consider using external hosting services like Netlify or Vercel."
          echo "::warning::Alternatively, use separate GitHub repositories for each PR preview."
          exit 1